export const POST_ERROR_CODES = {
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  INVALID_FORM_DATA: "INVALID_FORM_DATA",
  INVALID_JSON: "INVALID_JSON",
  INVALID_ID: "INVALID_ID",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  WRONG_PASSWORD: "WRONG_PASSWORD",
  POST_NOT_FOUND: "POST_NOT_FOUND",
  INVALID_TITLE: "INVALID_TITLE",
  MISSING_IMAGES: "MISSING_IMAGES",
  DUPLICATE_IMAGE_NAME: "DUPLICATE_IMAGE_NAME",
  TITLE_OR_SLUG_ALREADY_EXISTS: "TITLE_OR_SLUG_ALREADY_EXISTS",
  INVALID_EXTENSION: "INVALID_EXTENSION",
  UUID_COLLISION: "UUID_COLLISION",
  TRANSIENT_ERROR_RETRY_FAILED: "TRANSIENT_ERROR_RETRY_FAILED",
} as const

export type PostErrorCode = (typeof POST_ERROR_CODES)[keyof typeof POST_ERROR_CODES]

export type ErrorResponse<TError extends string = PostErrorCode> = {
  error: TError
}
